spring:
  application:
    name: cnh-be-service
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/new_db_cnh
    username: ${DB_USERNAME:new_cnh_root}
    password: ${DB_PASSWORD:Str0ngP@ssw0rId}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Logging Configuration
logging:
  level:
    com.cnh.ies: ${LOG_LEVEL:INFO}
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/cnh-be-service.log
    max-size: 100MB
    max-history: 30

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-make-it-long-and-secure}
  expiration: ${JWT_EXPIRATION:14400000} # 4 * 60 * 60 * 1000 = 4 hours in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:28800000} # 8 * 60 * 60 * 1000 = 8 hours in milliseconds

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket-name: ${AWS_S3_BUCKET:cnh-wms-bucket}
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}
  ses:
    from-email: ${AWS_SES_FROM_EMAIL:}
    region: ${AWS_SES_REGION:us-east-1}

# Azure Configuration
azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:}
    container-name: ${AZURE_STORAGE_CONTAINER:cnh-wms}

# SendGrid Configuration
sendgrid:
  api-key: ${SENDGRID_API_KEY:}
  from-email: ${SENDGRID_FROM_EMAIL:}

# File Upload Configuration
file:
  upload:
    max-size: 10MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,csv
    upload-dir: uploads/

# Business Rules Configuration
business:
  rules:
    order:
      max-items: 100
      max-total: 1000000
    payment:
      require-approval: true
      max-amount: 500000
    inventory:
      low-stock-threshold: 10
      critical-stock-threshold: 5

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# OpenTelemetry Configuration
otel:
  traces:
    exporter: otlp
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
  metrics:
    exporter: prometheus
  logs:
    exporter: otlp

# Custom Application Properties
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  security:
    bcrypt-strength: 12
    session-timeout: 3600
  cache:
    ttl: 3600
    max-size: 1000
